### PR TITLE
Dev Build for Commit 1f3cecc

### PR DESCRIPTION
**Pull request by janjagusch**
With this PR, I'm trying to build a dev package for this commit https://github.com/onnx/onnx/commit/1f3cecc6a07527dd132e416f78f5400667fa9e6f.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by janjagusch** [comment]
@conda-forge-admin, please rerender

**Comment by janjagusch** [comment]
@xhochy, could you take a look at this, please? I'm not 100% I did it correctly, but CI seems to pass.

**Comment by xhochy** [comment]
@janjagusch Can you add yourself as a maintainer (in a separate PR)?

**Comment by xhochy** [comment]
Otherwise this is LGTM. Once you are added as a maintainer, please create a `dev` branch and merge this PR to that branch.

**Comment by janjagusch** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please restart ci

**Pull request merged**
