### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by vinitra** [comment]
Hi @marcelotrevisani -- Is there any further progress on getting the windows build of ONNX released to conda-forge?

**Comment by marcelotrevisani** [comment]
> Hi @marcelotrevisani -- Is there any further progress on getting the windows build of ONNX released to conda-forge?

Not really... Windows is always a nightmare to compile anything :smile: 
As I do not have a windows machine, I cannot test locally

But feel free to apen a PR to add onnx on windows platform :)

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by ocefpaf** [comment]
@vinitra we are always looking for Windows expertise! That is a rare talent. If you can send a PR and help out with the Windows support it would be great!

**Comment by marcelotrevisani** [comment]
Closing in favour of https://github.com/conda-forge/onnx-feedstock/pull/47

**Pull request closed without merging**
