### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by anirudhacharya**
@bddppq

### CODE REVIEW

**Comment by bddppq** [comment]
@ezyang for double checking the protobuf minimum version change.

**Comment by dougalsutherland** [comment]
Protobuf 3.4 [isn't ABI- compatible](https://abi-laboratory.pro/tracker/timeline/protobuf/) with 3.5, so a single binary build can only support one version or the other. The conda-forge overall decision is to use 3.5; if you have some strong reason to want a build for 3.4 as well, we can do it in a branch, but it doesn't really seem worth it?

**Comment by bddppq** [comment]
@dougalsutherland thanks for the information.
@anirudhacharya any particular reason we need 3.4?

**Comment by anirudhacharya** [comment]
@bddppq @dougalsutherland  When I tried to install onnx v1.1.0 either via pip or via source build with the latest protobuf, the install failed with the message
```
This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers.
```
I was able to build only when the protoc version was the following
```
$ protoc --version
libprotoc 3.4.0
```
So I changed the protobuf requirements to 3.4

**Comment by dougalsutherland** [comment]
Hmm, I got the same error locally when I tried to build the recipe with protobuf 3.5:
```
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -m64 -I/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fPIC -DONNX_NAMESPACE=onnx -I/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0 -I/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0/third_party/pybind11/include -I/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include/python3.6m -I/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -I/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include/python3.6m -c /nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0/onnx/checker.cc -o build/temp.linux-x86_64-3.6/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0/onnx/checker.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0/onnx/onnx_pb.h:64:0,
                 from /nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0/onnx/checker.h:6,
                 from /nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0/onnx/checker.cc:1:
/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0/onnx/onnx.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0/onnx/onnx.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/nfs/nhome/live/dougals/anaconda/conda-bld/onnx_1521654753277/work/onnx-1.1.0/onnx/onnx.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
error: command 'gcc' failed with exit status 1
```
Looking into it....

**Comment by dougalsutherland** [comment]
Caused by https://github.com/onnx/onnx/issues/639: the version on PyPI currently only works with the same version of protobuf as whoever uploaded it used.

Will make a PR that builds from source instead of from PyPI, I think.

**Comment by anirudhacharya** [comment]
@dougalsutherland this change will also have to patched to the (ONNX v1.1.0 release)[https://github.com/onnx/onnx/releases/tag/v1.1.0] right?

**Comment by dougalsutherland** [comment]
@anirudhacharya Nope, luckily it just works if we install from the github source instead of from PyPI.

Closing this now in favor of #5 because of the onnx bug; thanks for your efforts. :)

**Pull request closed without merging**
