### PR TITLE
Enable win build

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by chinhuang007** [comment]
@marcelotrevisani Are you still on this? Any chance of getting Windows build in soon?

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani Are you still on this? Any chance of getting Windows build in soon?

lets give another try here
https://github.com/conda-forge/onnx-feedstock/pull/38

I deleted this branch

**Pull request closed without merging**
