### PR TITLE
enable windows build

### PR DESCRIPTION
**Pull request by clouds56**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by clouds56** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotrevisani** [comment]
Could you please resolve the conflicts? I think that should be good to go after that

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please rerender

**Comment by vinitra** [comment]
@clouds56 is there any progress on this PR?

**Comment by clouds56** [comment]
I'm not sure, let's first try rerender.
@conda-forge-admin, please rerender

**Comment by clouds56** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
