### PR TITLE
release 1.2.1

### PR DESCRIPTION
**Pull request by linkerzhang**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by linkerzhang** [comment]
@bddppq any idea about the lint comment above please? :) I'm a new bee on this.

**Comment by linkerzhang** [comment]
for ci failure in python 2.7. the error is,    
 from typing import Text, Sequence, Any, Optional, Dict, Union, TypeVar, Callable, Tuple, List, cast
ImportError: No module named typing
Hmmm, typing is new in 3.5, am I right?

**Comment by smessmer** [comment]
Python is included in python 3, and can be installed for python 2 using the "typing" package from pypi.  This should already be correctly set up as a dependency in setup.py. Are dependencies for conda defined somewhere differently?

**Comment by dougalsutherland** [comment]
Sorry for the very slow turnaround on this. Will fix in #17 once https://github.com/conda-forge/staged-recipes/pull/6263 is in.

**Pull request closed without merging**
